# Generated by Django 4.2.16 on 2024-11-14 03:43

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedProducts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_in_stock', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=255)),
                ('expired_date', models.DateField(verbose_name='Expiry Date')),
                ('main_image', models.CharField(max_length=255)),
                ('sub_image_1', models.CharField(max_length=255)),
                ('sub_image_2', models.CharField(max_length=255)),
                ('isAvailable', models.BooleanField(default=True, verbose_name='Is Available')),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bin_number', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('isDelete', models.BooleanField(default=False)),
                ('isFulled', models.BooleanField(default=True, verbose_name='Is Fulled')),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('capacity', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('isDelete', models.BooleanField(default=False)),
                ('isFulled', models.BooleanField(default=True, verbose_name='Is Fulled')),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterials',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(max_length=255)),
                ('image', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('quantity_in_stock', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=255)),
                ('expired_date', models.DateField(verbose_name='Expiry Date')),
                ('isAvailable', models.BooleanField(default=True, verbose_name='Is Available')),
                ('isDelete', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_materials', to='inventory.location')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('capacity', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('isDelete', models.BooleanField(default=False)),
                ('isFulled', models.BooleanField(default=True, verbose_name='Is Fulled')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('capacity', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('isDelete', models.BooleanField(default=False)),
                ('isFulled', models.BooleanField(default=True, verbose_name='Is Fulled')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='inventory.warehouse')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='materials',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='rack',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='inventory.zone'),
        ),
        migrations.AddField(
            model_name='location',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='inventory.rack'),
        ),
        migrations.AddField(
            model_name='finishedproducts',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finished_products', to='inventory.location'),
        ),
    ]
