# Generated by Django 4.2.16 on 2024-11-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_diy', '0002_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
