# Generated by Django 4.2.16 on 2024-11-22 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_diy', '0003_alter_clients_birth_alter_employees_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='db_diy.role'),
        ),
    ]
