# Generated by Django 4.2.16 on 2024-11-14 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
        ('db_diy', '0002_clients'),
        ('supplier', '0003_bankingdetail_representative_suppliers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesBill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_name', models.CharField(max_length=255)),
                ('invoice_number', models.CharField(max_length=255)),
                ('created_date', models.DateField()),
                ('due', models.DateField()),
                ('sub_total', models.IntegerField()),
                ('tax_rate', models.IntegerField()),
                ('tax_amount', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('total_amount_text', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_diy.clients')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sales_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.salesorder')),
            ],
        ),
        migrations.CreateModel(
            name='PurchasesBill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_name', models.CharField(max_length=255)),
                ('invoice_number', models.CharField(max_length=255)),
                ('created_date', models.DateField()),
                ('due', models.DateField()),
                ('sub_total', models.IntegerField()),
                ('tax_rate', models.IntegerField()),
                ('tax_amount', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('total_amount_text', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('purchases_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.purchaseorder')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.suppliers')),
            ],
        ),
    ]
